language: objective-c
osx_image: xcode6.4

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_WORKSPACE=ObjectMapper.xcworkspace
  matrix:
    - SCRIPT="xctool -workspace $XCODE_WORKSPACE -scheme ObjectMapper-iOS -sdk iphonesimulator test"
    - SCRIPT="xctool -workspace $XCODE_WORKSPACE -scheme ObjectMapper-Mac test"

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

script: $SCRIPT

notifications:
  email: false